version: "3"
services:
  mysql:
    image: mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    networks:
      - project
    environment:
      MYSQL_HOST: ${MYSQL_HOST:-localhost}
      MYSQL_USER: ${MYSQL_USER:-username}
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-password}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-db}
    volumes:
      - my-datavolume:/var/lib/mysql

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    networks:
      - project
    ports:
      - 8080:8080

  express:
    build:
      context: .
      dockerfile: Dockerfile
    image: express
    container_name: express
    networks:
      - project
    ports:
      - 3000:3000
    depends_on:
      - mysql

networks:
  project:
    external: false
    driver: bridge

volumes:
  my-datavolume:
    driver: local
